print("bonus mentions in every anime here")
print("one piece: THE ONE PIECE IS REAAAALLL!!!")
print("jujutsu kaisen: nah, i'd win.")
print("one punch man: idk")
print("JJBA: AWAGDSAGHAFHAGSDF JOJO REFERENCE!!!!")
print("death note: the live action movie i guess idk")
print("attack on titan: the hate on the new season")
print("naruto: boruto")
print("dragon ball Z: the owner of dragon ball Z dying")
print("demon slayer: the animation???")
print("my hero academia: the fans on tiktok from last year")